{% set name = "interchange" %}
{% set version = "2021.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/interchange-{{ version }}.tar.gz
  sha256: 6791d1b34621e990035fe75d808523172340d80ade1b50412226820184199550

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pytz
    - six

test:
  imports:
    - interchange
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/py2neo-org/interchange
  summary: Data types and interchange formats
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - motey
    - marimeireles
